### ISSUE TITLE
"This software cannot be used. The Nintendo Network ID used to purchase" When Installing a Build From Unity

### ISSUE THREAD

**Issue by one-and-only** [RetroAndDev/WiiUCafeSDKDeluxe#5]
Hello. I hope you aren't terribly busy. I have installed a build of the most basic Unity game possible on my Wii U after packaging it with this software. The problem is that every time I run it (with network or not, development build or not) it shows the error in the title. I did some research and normally this would be due to not having bypassed signature checks. However, I do have the appropriate 01_sigpatches.rpx file in the proper location and verified that deleting that file affects certain operations of other homebrew software that I have installed. Then I found that there is a small chance that my install files are not properly generated. 

My Wii U development environment is as follows:

* Unity `2017.1.2p3` (With Wii U Support installed)
* GHS MULTI Compiler `v5327`
* Wii U Cafe SDK Deluxe `v1.2.0`
* Wii U Cafe SDK `2.12.13`
* Wii U System Software `v5.5.6 (USA)`
* Title ID:` 0x01000`, `Variation 0x97`

Unity Build Settings:
* Build Debug Level: `Master [No Network]`
* Build Output: `Download Image`
* Boot Mode: `NAND`

If you need any more information, don't hesitate to let me know. I appreciate your help in advance.

**Comment by RetroAndDev** [comment]
Hummm
Never got this issue, I'm on a European Unit (Software 5.5.5). Someone already notified me of this issue. 
You are running a modded Wii U I assume ? What mod you use and how you installed your build ? 
I cannot confirm if this is due to sigpatches. I never had the issue on my side. 
To confirm if it is your mod who is not correctly configured or something else (I don't think it is from the Unity or WiiUCSDKDeluxe, you have your build settings correctly configured.) send me by email your build file (raw from Unity and after passing them in Wii U Cafe SDK Deluxe). I will try on my European Wii U. You will find it on my GitHub profile

**Comment by one-and-only** [comment]
Yes, I am running a modded Wii U. I have both the latest Aroma and Tiramisu environments installed, both of them having the sigpatch file installed and running on startup. Neither environment could fully launch the app, both getting the same error. I'll send the build files over to you shortly. You should see an email from `bdpaboi123@gmail.com`. Thanks again.

**Comment by one-and-only** [comment]
apologies for the small delay. Google Drive artificially limited my upload speed. The email should be sent now.

**Comment by one-and-only** [comment]
Also, I have a quick question. Are the Master Editor Tool and App Config Tool no longer available from Nintendo? I am unable to get anything from the Nintendo Development Portal or NDI. Any legitimate 3rd party site I can get these from?

**Comment by one-and-only** [comment]
Me and the author solved this issue via email. The solution was to match the Title ID inside WiiUCafeSDKDeluxe with the Title ID in the Unity project.
